#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm test
if [ $? -ne 0 ]; then
  echo "Tests failed. Push aborted."
  exit 1
fi

pnpm lint
if [ $? -ne 0 ]; then
  echo "Linting failed. Push aborted."
  exit 1
fi

# --- IGNORE ---
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# --- IGNORE ---
